### ISSUE TITLE
timetk holidays and weekdays

### ISSUE THREAD

**Issue by FelipeCarrillo** [business-science/timetk#10]
Matt; 
I apologize for the confusion, so let's go back to the original question. The problem that I am having is with holidays and weekends. Please try to run all the code below to see if you get error messages.
After running this:
new_data <- train %>%
    tk_index() %>%
    tk_make_future_timeseries(n_future = 252, skip_values = holidays, inspect_weekdays = TRUE) %>%
    tk_get_timeseries_signature()
new_data has only 173 records because holidays and weekends have been removed but actual_future still has 252 so they cannot been cbind together.

RUN FULL SCRIPT BELOW
library(timetk)
library(tidyquant)

FB_tbl <- FANG %>%
    filter(symbol == "FB") %>%
    select(date, volume)
FB_tbl

# Everything before 2016 will be used for training (2013-2015 data)
train <- FB_tbl %>%
    filter(date < ymd("2016-01-01"))
    dim(train)
     
# Everything in 2016 will be used for comparing the output
actual_future <- FB_tbl %>%
    filter(date >= ymd("2016-01-01"))
    dim(actual_future)
    
    train <- tk_augment_timeseries_signature(train)
train

fit_lm <- lm(volume ~ ., data = train[,-1])
summary(fit_lm)

# US trading holidays in 2016
holidays <- c("2016-01-01", "2016-01-18", "2016-02-15", "2016-03-25", "2016-05-30",
              "2016-07-04", "2016-09-05", "2016-11-24", "2016-12-23", "2016-12-26",
              "2016-12-30") %>%
    ymd()
     
# Build new data for prediction: 3 Steps
new_data <- train %>%
    tk_index() %>%
    tk_make_future_timeseries(n_future = 252, skip_values = holidays, inspect_weekdays = TRUE) %>%
    tk_get_timeseries_signature()
# New data should look like this
new_data

# Prediction using a linear model, fit_lm, on future index time series signature
pred_lm <- predict(fit_lm, newdata = new_data)
 length(pred_lm)

# Add predicted values to actuals data
actual_future <- actual_future %>%
    add_column(yhat = pred_lm)
    actual_future
######I GET AN ERROR HERE BECAUSE HOLIDAYS AND WEEKENDS HAVE NOT BEEN REMOVED FROM actual_data and therefore one dataset has 252 records and new data has only 173.  `

**Comment by mdancho84** [comment]
There are two issues:

1. `timetk` was updated to work off of `n_future` = total periods including missing dates. It used to be `n_future` = total periods excluding missing dates, but this was not intuitive and inconsistent with other packages such as `prophet` that include similar functionality.
2. Your holidays don't match the actual dates. You are excluding two dates that are present in your `actual_future` data frame.

```
# Change to total periods including missing dates, n_future = 365
new_data <- train %>%
    tk_index() %>%
    tk_make_future_timeseries(n_future = 365, skip_values = holidays, inspect_weekdays = TRUE) %>%
    tk_get_timeseries_signature()

# Check differences
setdiff(actual_future$date, new_data$index) %>% as_date()
>>> "2016-12-23" "2016-12-30"

# Adjust holidays
holidays <- c("2016-01-01", "2016-01-18", "2016-02-15", "2016-03-25", "2016-05-30",
              "2016-07-04", "2016-09-05", "2016-11-24", "2016-12-26") %>%
    ymd()

# Try again with holidays adjusted
new_data <- train %>%
    tk_index() %>%
    tk_make_future_timeseries(n_future = 365, skip_values = holidays, inspect_weekdays = TRUE) %>%
    tk_get_timeseries_signature()

setdiff(actual_future$date, new_data$index) %>% as_date()
>>> [1] "Date of length 0"
```
You should be able to get your intended 252 records.

**Comment by FelipeCarrillo** [comment]
Matt;
That is more less what I was needing clarification on. One last question related to holiday if you don't mind. So in order for tk_make_future_timeseries() to work, the holidays MUST be listed on both the train and test (in this case actual_future) data?

**Comment by mdancho84** [comment]
The future dates, `tk_make_future_timeseries()`, are influenced by four argument: 
- `inspect_weekdays`
- `inspect_months`
- `skip_values`
- `insert_values`

You need to determine a strategy to remove the dates in the future set. Please go through the [third vignette: making a future time series index](https://business-science.github.io/timetk/articles/TK02_Making_A_Future_Time_Series_Index.html). The answers you seek are in the document.

**Comment by FelipeCarrillo** [comment]
Thank you very much for this great package. I use forecast a lot for fish predictions and having the dates along the X axis is really great instead of having integers.

**Comment by mdancho84** [comment]
You are very welcome. It's a common complaint of the ts system of dates as numbers. I'm glad you're getting some use. Made my life way easier too!
