### ISSUE TITLE
Error in plot_acf_diagnostics()

### ISSUE THREAD

**Issue by samuelmacedo83** [business-science/timetk#100]
Hi Matt, 
I think I found a little bug when I run `plot_acf_diagnostics()`

```
Error in str_c("CCF_", .) : could not find function "str_c"
```

I think the issue is that you missed `stringr::str_c` [here](https://github.com/business-science/timetk/blob/693c329c61e906d7c26bbe0194fa09a956c2a35e/R/diagnostics-tk_acf_diagnostics.R#L194).

If you approve, I can send a PR fixing this. 

I'm your student in your time series course and it is really amazing. I'm learning a lot... Thanks :)

**Comment by mdancho84** [comment]
Great find! Sure thing on the PR. Just put it together and I'll approve. 

And thanks for joining the Time Series Course. I love that course.

**Comment by mdancho84** [comment]
Closing this. Should be fixed now.
