### ISSUE TITLE
offset parameter in step_log_interval not working properly

### ISSUE THREAD

**Issue by pablovalledor** [business-science/timetk#103]
step_log_interval function seems not to be taken offset parameter into account (limit_upper value wrongly calculated).

First Transformation in next example with offset = 0 reaches a limit_upper = 20.89 (properly calculated).
Second Transformation in next example with offset = 10 reaches a limit_upper = 20.89 (incorrect. It should be 30.89).

Reproducible example:
### First transformation
df <-as.data.frame(c(10, 5, 3, 5, 15, 18 ,19, 4, 0.1, 10))
colnames(df) <- "value"
recipe_test_transformation <- recipe(value ~ ., data = df) %>%
  step_mutate( value_trans = value) %>%
  step_log_interval( value_trans, limit_lower = 0, limit_upper = "auto", offset = 0) 
recipe_test_transformation_trained <- recipe_test_transformation %>% prep()
limit_lower <- recipe_test_transformation_trained $steps[[2]]$limit_lower_trained
limit_upper <- recipe_test_transformation_trained $steps[[2]]$limit_upper_trained
offset      <- recipe_test_transformation_trained $steps[[2]]$offset
limit_upper
$value_trans
[1] 20.89

### Second Transformation
recipe_test_transformation <- recipe(value ~ ., data = df) %>%
  step_mutate( value_trans = value) %>%
  step_log_interval( value_trans, limit_lower = 0, limit_upper = "auto", offset = 10) 
recipe_test_transformation_trained <- recipe_test_transformation %>% prep()
limit_lower <- recipe_test_transformation_trained $steps[[2]]$limit_lower_trained
limit_upper <- recipe_test_transformation_trained $steps[[2]]$limit_upper_trained
offset      <- recipe_test_transformation_trained $steps[[2]]$offset

limit_upper
$value_trans
[1] 20.89

**Comment by mdancho84** [comment]
Will take a look for the next version of timetk.

**Comment by mdancho84** [comment]
This should be fixed now. 

``` r
library(dplyr)
library(timetk)
library(recipes)

df <-tibble( value = c(10, 5, 3, 5, 15, 18 ,19, 4, 0.1, 10))

df %>%
    mutate(value_trans = log_interval_vec(value, limit_lower = 0, offset = 10))
#> log_interval_vec(): 
#>  Using limit_lower: 0
#>  Using limit_upper: 30.89
#>  Using offset: 10
#> # A tibble: 10 x 2
#>    value value_trans
#>    <dbl>       <dbl>
#>  1  10        0.608 
#>  2   5       -0.0576
#>  3   3       -0.319 
#>  4   5       -0.0576
#>  5  15        1.45  
#>  6  18        2.27  
#>  7  19        2.73  
#>  8   4       -0.188 
#>  9   0.1     -0.722 
#> 10  10        0.608


recipe_test_transformation <- recipe(value ~ ., data = df) %>%
    step_mutate( value_trans = value) %>%
    step_log_interval( value_trans, limit_lower = 0, limit_upper = "auto", offset = 10)

recipe_test_transformation_trained <- recipe_test_transformation %>% prep()
#> $value_trans
#> [1] 0
#> 
#> $value_trans
#> [1] 30.89

limit_lower <- recipe_test_transformation_trained $steps[[2]]$limit_lower_trained
limit_upper <- recipe_test_transformation_trained $steps[[2]]$limit_upper_trained
offset      <- recipe_test_transformation_trained $steps[[2]]$offset

limit_upper
#> $value_trans
#> [1] 30.89
```

<sup>Created on 2022-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
