### ISSUE TITLE
Apparent (essentially) cyclic dependency for timetk + tidyquant

### ISSUE THREAD

**Issue by MichaelChirico** [business-science/timetk#113]
I am trying to update `timetk` but don't have `tidyquant` available.

As such basically all of the examples in `timetk` fail, e.g.

https://github.com/business-science/timetk/blob/0d615900632ad2b449dc1fcec4a5f9540adba4c1/man/slidify.Rd#L91

(I count 30 .Rd using `library(tidyquant)`).

Of course, `tidyquant` itself Imports `timetk`, so I am struggling to update both at the same time.

Would it make sense to be more diligent in the `timetk` examples about when exactly `tidyquant` is needed, and to conditionalize examples with `requireNamespace("tidyquant")`?

**Comment by mdancho84** [comment]
Hey there, thanks for using `timetk`. `tidyquant` is not a required dependency of `timetk`, which would be illegal (a cyclic dependency) as you call it. 

But, if you look at the description. https://github.com/business-science/timetk/blob/0d615900632ad2b449dc1fcec4a5f9540adba4c1/DESCRIPTION#L49

You'll see that `tidyquant` is actually in the `Suggest`, which means its not required to run the package. 

Now regarding the examples and vignettes, some examples use the FANG dataset from `tidyquant`, so you'll need to install it to run the examples.

**Comment by MichaelChirico** [comment]
Allow me to clarify -- I didn't mean that there's a strict cyclic
dependency (obviously a violation of CRAN policy), but rather that there is
_effectively_ a dependence on tidyquant because of how heavily the examples
rely on it.

My suggestion to have examples run conditionally is in line with the CRAN
recommendation:

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages

> Note that someone wanting to run the examples/tests/vignettes may not
have a suggested package available (and it may not even be possible to
install it for that platform). The recommendation used to be to make their
use conditional via if(require("pkgname")): this is OK if that conditioning
is done in examples/tests/vignettes, although using
if(requireNamespace("pkgname")) is preferred, if possible.
