### ISSUE TITLE
plot_time_series error when using .trelliscope = TRUE

### ISSUE THREAD

**Issue by AristosK** [business-science/timetk#122]
plot_time_series gives an error when using trelliscope  in timetk 2.8.1.

Minimal reproducible example:

m4_daily %>%
  group_by(id) %>%
  plot_time_series(date, value,
                   .facet_ncol = 2, .facet_scales = "free",
                   .interactive = TRUE,.plotly_slider = TRUE,.trelliscope = TRUE)
                   
gives followng error:

Error in `bind_cols()`:
! `..1` must be a vector, not a <grouped_df/tbl_df/tbl/data.frame/cognostics> object.

**Comment by mdancho84** [comment]
Hey this works in the latest version of `timetk >= 2.8.1`

``` r
remotes::install_github("business-science/timetk")
```

## Solution

``` r
library(tidyverse)
library(timetk)


m4_daily %>%
    group_by(id) %>%
    plot_time_series(
        date, value,
        .facet_ncol    = 2, 
        .facet_scales  = "free",
        .interactive   = TRUE,
        .plotly_slider = TRUE,
        .trelliscope   = TRUE
    )
```
![image](https://user-images.githubusercontent.com/13734662/175819018-1b91a0b3-129d-416d-b34c-4be4297067aa.png)

**Comment by mdancho84** [comment]
Note - It does look like the .plotly_slider does not have an effect with Trelliscope (news to me). But I could get trelliscope to work.

**Comment by AristosK** [comment]
Great, its working fine now, thank you for looking into this

**Comment by mdancho84** [comment]
Excellent!
