### ISSUE TITLE
Suggestion: add .x_intercept for plot_time_series

### ISSUE THREAD

**Issue by mabuimo** [business-science/timetk#131]
I think that adding an .x_intercept and .x_intercept color would be very useful for time series where we have historical data and predicted values so that we can signpost when the historical data finishes. If we can shadow in grey the predictions or change the line to a dashed one, even better. Thanks.

**Comment by mdancho84** [comment]
Good suggestion. Done. 

``` r
library(tidyverse)
library(tidyquant)
library(lubridate)
library(timetk)

# Works with individual time series
FANG %>%
    filter(symbol == "FB") %>%
    plot_time_series(
        date, adjusted, 
        .x_intercept = c(as_date("2015-01-01"), as_date("2016-01-01")),
        .x_intercept_color = "red",
        .interactive = FALSE
    )
```

![](https://i.imgur.com/vijTQgS.png)

``` r

# Works with groups
FANG %>%
    group_by(symbol) %>%
    plot_time_series(
        date, adjusted, 
        .x_intercept = c(as_date("2015-01-01"), as_date("2016-01-01")),
        .x_intercept_color = "red",
        .facet_ncol  = 2,
        .interactive = FALSE
    )
```

![](https://i.imgur.com/PxzfHuM.png)

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
