### ISSUE TITLE
terms_select deprecated

### ISSUE THREAD

**Issue by gouthaman87** [business-science/timetk#133]
`terms_select()` was deprecated in recipes 0.1.17.
ℹ Please use `recipes_eval_select()` instead.

**Comment by mdancho84** [comment]
Please update to the latest version of `timetk`. You are likely using an older version.

**Comment by joranE** [comment]
I think that this was fixed in a pull request from me that was only merged on Aug 18th but the most recent version on CRAN is from May. So I think this hasn't made it into the CRAN version yet. Installing the dev version from github would be an option, though.
