### ISSUE TITLE
Conflict in tk_xts when time variable is called `time`

### ISSUE THREAD

**Issue by JoseAntonioOrtega** [business-science/timetk#15]
It gives an error:

`timeError in xts(x = list(obsvalue = c(10.61, 10.57, 10.55, 10.47, 10.41,  : 
  order.by requires an appropriate time-based object`

Reproducible example:

```
library(tidyverse)
library(tidyquant) 
library(ecb) 
library(tibbletime)
library(timetk) 

unemp=get_data("STS.M.I8.S.UNEH.RTT000.4.000") %>% 
  mutate(time=convert_dates(obstime)) %>%         
  as_tbl_time(index=time)
unemp %>% tk_xts()
```
If the time variable is called something different, like `month`, it works fine.

The code also worked fine using `timekit`.

**Comment by mdancho84** [comment]
Thanks, I'll take a look!

**Comment by mdancho84** [comment]
I don't believe this is a `timetk` issue. The following works. Closing the issue. 

```
library(tidyverse)
library(tidyquant)
library(timetk)

aapl_tbl <- tq_get("AAPL")

aapl_tbl %>%
    rename(time = date) %>%
    tk_xts()
```
