### ISSUE TITLE
problem to install timetk

### ISSUE THREAD

**Issue by olidarne** [business-science/timetk#151]
I tried to install timetk package from CRAN and github but I have obtained the results:

** byte-compile and prepare package for lazy loading
Erreur dans loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  l'espace de noms 'rlang' 1.1.0 est en train de charger, mais >= 1.1.1 est requis
Appels : <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Exécution arrêtée
ERROR: lazy loading failed for package 'tidymodels'
* removing 'C:/Users/darne-o/Documents/R/win-library/4.1/tidymodels'
ERROR: dependency 'tidymodels' is not available for package 'timetk'
* removing 'C:/Users/darne-o/Documents/R/win-library/4.1/timetk'

The downloaded source packages are in
        ‘C:\Users\darne-o\AppData\Local\Temp\Rtmp2jSLk1\downloaded_packages’
Messages d'avis :
1: Dans install.packages("timetk") :
  installation of package ‘tidymodels’ had non-zero exit status
2: Dans install.packages("timetk") :
  installation of package ‘timetk’ had non-zero exit status

I tried to install the 1.1.1 version of rlang because The 1.1.0 is installed but without succeed...
> packageVersion("rlang")
[1] ‘1.1.0’
> remove.packages("rlang")
Elimination du package de ‘C:/Users/darne-o/Documents/R/win-library/4.1’
(car ‘lib’ n'est pas spécifié)
> install.packages("rlang", version="1.1.1")
> packageVersion("rlang")
[1] ‘1.1.0’

It appears that without this version of rlang I do not succed to install tidymodels and timetk

**Comment by mdancho84** [comment]
Delete rlang. Then reinstall rlang. 

Then retry timetk.

**Comment by olidarne** [comment]
I did that but when installing rlang it was the 1.1.0 version which was installed and then the installation of timetk did not succeed. 
I deleted rlang from remove.packages and also directly on my library. 
I used the 4.1.1 version of R ...
Finally, I installed the lastest version 4.3.1 and now all is ok!

**Comment by mdancho84** [comment]
Ah ok. Thanks for letting me know. Just a heads up I know you have been working hard on helping improve some stuff in timetk and tidyquant. It will be a bit before I can focus on that stuff. But keep it coming.
