### ISSUE TITLE
ymd vs POSIXlt

### ISSUE THREAD

**Issue by isomorphisms** [business-science/timetk#17]
from the "working with time series" vignette:

> The index gives the user a lot of information in a simple timestamp. Consider the datetime “2016-01-01 00:00:00”. From this timestamp, we can decompose the datetime to get the signature, which consists of the year, quarter, month, day, day of year, day of month, hour, minute, and second of the occurrence of a single observation.

Actually if I saw a `00:00:00` with that much precision, I would assume the time is actually unknown and I am really working with `lubridate::ymd` data, which in R type datasets is more common than a precise UTC value.

**Comment by mdancho84** [comment]
YMD has no time information or timezone. It's just date (month, quarter, day, etc).
