### ISSUE TITLE
Inconsistent output length with tk_make_future_timeseries

### ISSUE THREAD

**Issue by erbas** [business-science/timetk#19]
So this package is amazing, thank you! But it's most useful feature is a little broken. Suppose I want to make forecast for the next 60 business days. If I understand correctly, I should use this function:

`idx.pred <- tk_make_future_timeseries(index(df.train), 60, inspect_weekdays = TRUE) `

The problem is that depending on where the weekends fall in my out of sample data, the `tk_make_future_timeseries()` call returns a different length vector. Rather than returning the next sixty business days, it looks like it's taking the calendar for the next sixty days and dropping the weekends. This is a disaster, because `pred.xts <- xts(pred, idx.pred)` fails with an error about series needing to be the same length as their dates.

**Comment by mdancho84** [comment]
This should be taken care of. I have implemented a new argument `length_out` that defines:
1. The number of observations if a numeric value is used (e.g. `length_out = 365` always returns 365 observations despite if weekends are removed or business holidays are removed).
2. The end date if a time-based duration is used (e.g. `length_out = "1 year"` returns all observations within 1-year from the end date of the incoming index. This means you might only get 252 days if weekends and business holidays are removed).

I will release to CRAN in the next few weeks, but until then, try the devtools::install_github("business-science/timetk").
