### ISSUE TITLE
tk_make_future_timeseries does not correctly handle timezones.

### ISSUE THREAD

**Issue by JustGitting** [business-science/timetk#20]
Hi, 

I'm trying to use an index based on POSIXct with the timezone set to a non UTC zone. Unfortunately, the tk_make_future_timeseries() does not handle the creation of future time series correctly when the timezone has been set to something other than UTC.

The first example is based on the one given for the tk_make_future_timeseries() function, that works as expected.
```
idx <- c("2015-04-01 00:00:00",
         "2015-04-01 01:00:00",
         "2015-04-01 02:00:00") %>%
  ymd_hms()
idx
idx %>%
  tk_make_future_timeseries(n_future = 3)
```
[1] "2015-04-01 03:00:00 UTC" "2015-04-01 04:00:00 UTC" "2015-04-01 05:00:00 UTC"

However, once we set a time zone for the idx, things get weird...

```
idx <- c("2015-04-05 00:00:00",
         "2015-04-05 01:00:00",
         "2015-04-05 02:00:00") %>%
  ymd_hms(tz = 'Africa/Bujumbura')
idx
idx %>%
  tk_make_future_timeseries(n_future = 3)

```
[1] "2015-04-05 01:00:00 CAT" "2015-04-05 02:00:00 CAT" "2015-04-05 03:00:00 CAT"
Here, the Bujumbura future time series starts in the middle of the idx time series.

```
idx <- c("2015-04-01 00:00:00",
         "2015-04-01 01:00:00",
         "2015-04-01 02:00:00") %>%
  ymd_hms(tz = 'Hongkong')
idx
idx %>%
  tk_make_future_timeseries(n_future = 3)

```
[1] "2015-03-31 19:00:00 HKT" "2015-03-31 20:00:00 HKT" "2015-03-31 21:00:00 HKT"

The Hong Kong future time series starts before the idx time series starts, which is not expected.

A (inefficient??) work-around is to convert the posixct to numerical values, then back again after calling 
tk_make_future_timeseries()

```
idx <- c("2015-04-01 00:00:00",
         "2015-04-01 01:00:00",
         "2015-04-01 02:00:00") %>%
  ymd_hms(tz = 'Hongkong')
idx

idx.future <- as.numeric(idx) %>%
  tk_make_future_timeseries(n_future = 3)

as.POSIXct(idx.future, origin = '1970-01-01 00:00:00', tz = 'Hongkong')
```
"2015-04-01 03:00:00 HKT" "2015-04-01 04:00:00 HKT" "2015-04-01 05:00:00 HKT"
Hence we get the expected future time series.

I hope this can be fixed as timetk looks to be a very useful toolbox that helps with many of the compatibility issues between the Pantheon of time series packages.

**Comment by mdancho84** [comment]
I'm looking into this for all of the `tk_make_*` functions. `tk_make_timeseries()` the more flexible version of `seq.Date()` and `seq.POSIXt()` also likely suffers from this. I will address soon.

**Comment by mdancho84** [comment]
This should be taken care of. I will release to CRAN in the next few weeks, but until then, try the `devtools::install_github("business-science/timetk")`.
