### ISSUE TITLE
Overlap between tibbletime, timetk and tsibble

### ISSUE THREAD

**Issue by adrfantini** [business-science/timetk#22]
Hi!
`tibble`s are extended to deal with time in three packages (that I know of!): `timetk`, `tibbletime` and `tsibble`. I'm still trying to understand which package is best suited to use for what, and I find they have quite an overlap.

I know the former two packages are both created by you, have you considered joining forces with `tsibble`'s author to create a single, complete package?

Thanks for the nice packages!

**Comment by mdancho84** [comment]
Hi @adrfantini , I have a table on the `timetk` homepage that discusses the new mission and how `timetk` now compares. 

![image](https://user-images.githubusercontent.com/13734662/80595624-0c060200-89f3-11ea-9e85-d414540aba72.png)

**Comment by adrfantini** [comment]
That's very nice, thank you!
