### ISSUE TITLE
Error on coersion from data.table to xts

### ISSUE THREAD

**Issue by quantitative-technologies** [business-science/timetk#23]
I have a `data.table` called `dt` with a `POSIXct` column called `timestamp`. 

    > tk_xts(dt, date_var = timestamp)

gives the error: `Error in !syms : invalid argument type`. I tracked it down to line 11 of `tk_xts_.data.frame` where this call is made:

    ret <- dplyr::select_if(ret, is.numeric)

**Comment by mdancho84** [comment]
This seems to work for me. Closing the issue. 

```
library(tidyverse)
library(tidyquant)
library(timetk)
library(data.table)

aapl_tbl <- tq_get("AAPL")

aapl_dt <- aapl_tbl %>%
    rename(timestamp = date) %>%
    data.table::as.data.table()

aapl_dt %>% tk_xts()

```

**Comment by quantitative-technologies** [comment]
Unfortunately, I didn't make an MRE, and I cannot recall which data set caused this. 

Just FYI.

**Comment by mdancho84** [comment]
OK, well take a look at my example. I tried to replicate a problem, but everything seemed to work.
