### ISSUE TITLE
Error in tk_get_timeseries_summary

### ISSUE THREAD

**Issue by junkka** [business-science/timetk#28]
tk_get_timeserie_summary returns an error

```r
library(tidyquant)
library(timetk)
library(tidyverse)

data(FANG, package = "tibbletime")

# Works with time-based tibbles
FB_tbl <- FANG %>% filter(symbol == "FB")
FB_idx <- tk_index(FB_tbl)

tk_get_timeseries_summary(FB_idx)
```

    Error in dimnames(x) <- dnx : 'dimnames' applied to non-array

The issue originates from the `get_timeseries_summary_date` function when trying to tidy a summary table object using `broom::tidy`. This might be a result of `broom::tidy.table` now being deprecated. 

A working fix is to substitute the `broom:tidy` function with `as.list`

As I stumbled upon this issue when using the [`anomalize`](https://github.com/business-science/anomalize) package I am not sure what kind #of output the `broom::tidy.table` would provide if it worked as intended. Using the suggested fix the output would look like this: 

```
# A tibble: 1 x 12
  n.obs start      end        units scale tzone diff.Min. `diff.1st Qu.` diff.Median
  <int> <date>     <date>     <chr> <chr> <chr>     <dbl>          <dbl>       <dbl>
1  1008 2013-01-02 2016-12-30 days  day   UTC       86400          86400       86400
# … with 3 more variables: diff.Mean <dbl>, `diff.3rd Qu.` <dbl>, diff.Max. <dbl>
```

**Comment by junkka** [comment]
The correct output should be

```
# A tibble: 1 x 12
  n.obs start      end        units scale tzone diff.minimum diff.q1 diff.median
  <int> <date>     <date>     <chr> <chr> <chr>        <dbl>   <dbl>       <dbl>
1  1008 2013-01-02 2016-12-30 days  day   UTC          86400   86400       86400
# … with 3 more variables: diff.mean <dbl>, diff.q3 <dbl>, diff.maximum <dbl>
```

**Comment by mdancho84** [comment]
This should be fixed.
