### ISSUE TITLE
tk_index warning

### ISSUE THREAD

**Issue by FelipeCarrillo** [business-science/timetk#31]
Hi; 
I just downloaded the latest release of timetk and I am getting a warning when using the tk_index function. It still works but was wondering if there is a woraround because eventually is going to turn into an error. Thanks
> idx <- tk_index(pond)
Warning message:
'xts::indexTZ' is deprecated.
Use 'tzone' instead.
See help("Deprecated") and help("xts-deprecated").

**Comment by mdancho84** [comment]
Hi, I'll fix it during the next routine update.

**Comment by mdancho84** [comment]
This should be fixed now.
