### ISSUE TITLE
plot_seasonal_diagnostics errors on ungrouped tibble

### ISSUE THREAD

**Issue by robotmasterkris** [business-science/timetk#34]
```R
taylor_30_min %>%
  plot_seasonal_diagnostics(date, value, .interactive = FALSE)
```

Returns `Error in if (facet_groups == "") facet_groups <- "." :  argument is of length zero`.

Suggests that the function is not compatible with ungrouped dataframes. 

The following modification produces the expected result:

```R
taylor_30_min %>%
  mutate(id = "id") %>%
  group_by(id) %>%
  plot_seasonal_diagnostics(date, value, .interactive = FALSE)
```

**Comment by mdancho84** [comment]
Hmmm... It works for me. Please try the development version. 

```
taylor_30_min %>%
  plot_seasonal_diagnostics(date, value, .interactive = FALSE)
```

![image](https://user-images.githubusercontent.com/13734662/82886780-011c8f80-9f15-11ea-9c3b-fbe435279283.png)

**Comment by mdancho84** [comment]
Closing - Let me know if this happens again.
