### ISSUE TITLE
Installing timetk via CRAN vs. MRAN

### ISSUE THREAD

**Issue by MichaelKurz1988** [business-science/timetk#35]
I am trying to install timetk from the Microsoft R Open (version 3.5.2) distribution ([https://mran.microsoft.com](https://mran.microsoft.com)).  Unfortunately,  `install.packages("timetk")`  installs package version 0.1.1.1, which is not usable. It does not include most of the package's functions. Checking ([https://mran.microsoft.com](https://mran.microsoft.com)) it says that package version 1.0.0.0 should be available, which is the same as is available via CRAN. So, I am not really sure what is happening.

My company only allows me to install packages via ([https://mran.microsoft.com](https://mran.microsoft.com)). So, I cannot install it via CRAN or from the Git repository. Could any of the contributors please check the version available via Microsoft R Open and if necessary update it?

**Comment by AlexPars** [comment]
My suggestions: 1) use checkpoint package to specify the snapshot date and 2) use cran.microsoft.com

**Comment by mdancho84** [comment]
Hi Michael, 
This is an issue with MRAN and not `timetk`, so unfortunately I cannot help. The `timetk` package is going through a very large upgrade right now. It may take a while for MRAN to catch up. But eventually they will. Just recognize that MRAN is not CRAN, and their packages may differ in what is available. 
-Matt
