### ISSUE TITLE
Plot Anomaly Diagnostics

### ISSUE THREAD

**Issue by mmosquerab** [business-science/timetk#37]
Hi, I just updated my RStudio to version 4.0.0 but I encountered the following error while running the # 2.0 Anomaly Detection line:

bike_sharing_daily %>%
plot_anomaly_diagnostics(
dteday,
log(cnt)
)
Error in plot_anomaly_diagnostics(., dteday, log(cnt)) :
no se pudo encontrar la función "plot_anomaly_diagnostics"

Any advice on this?

**Comment by mdancho84** [comment]
This is because CRAN does not yet have `timetk` 2.0.0 (just sent over the weekend). 

Solution: Install the development version. `devtools::install_github("business-science/timetk")`
