### ISSUE TITLE
Problem with plot_seasonal_diagnostics

### ISSUE THREAD

**Issue by jtrommel** [business-science/timetk#39]
I copied your example of plot_seasonal_diagnostics but it gives the following error message:
> taylor_30_min %>%
+     plot_seasonal_diagnostics(date, value, .interactive = FALSE)
Error in if (facet_groups == "") facet_groups <- "." : 
  argument is of length zero

**Comment by mdancho84** [comment]
@jtrommel This seems to work for me. 

```
taylor_30_min %>% plot_seasonal_diagnostics(date, value, .interactive = F)
```
![image](https://user-images.githubusercontent.com/13734662/85809439-e01ea880-b725-11ea-94eb-a5b3e4e61755.png)

**Comment by mdancho84** [comment]
Closing this issue.
