### ISSUE TITLE
pad_by_time passing start_val and end_val for regular grouped datasets

### ISSUE THREAD

**Issue by good-marketing** [business-science/timetk#42]
Hi Matt,

Super nice package once again!  I was working with pad_by_time, and my goal was to create a grouped regular time series, in such a way that each group has exactly the same amount of rows (=intervals). The only way I could figure it out was to use the start_val  = min(date$data) and end_val  = max(date$data) directly in part::pad. So maybe it would be nice to have these params available to the user in  pad_by_time. 

Alternatively, perhaps auto-creating this grouped regular time series using a separate parameter (for example .regular = T) could do the job for the user. 

Thanks,

Bob

**Comment by mdancho84** [comment]
Thanks for the kind comments. I've just added the arguments, `pad_by_time(.start_date = NULL, .end_date = NULL)`. You should now be able to expand/contract the windows when padding your time series data.

You can find a minimal example in the [Function Reference](https://business-science.github.io/timetk/reference/pad_by_time.html).

![image](https://user-images.githubusercontent.com/13734662/87807143-e932ff00-c825-11ea-9561-4631a9c63a07.png)

**Comment by mdancho84** [comment]
Note that you will need to install the development version. These changes will be included in the next CRAN version, `timetk` 2.2.0.
