### ISSUE TITLE
White Noise Bounding

### ISSUE THREAD

**Issue by realauggieheschmeyer** [business-science/timetk#43]
Hey Matt,

I know that you based a lot of the functionality within `timetk` and `modeltime` on the `forecast` package (and I can only assume its spiritual successors, `fable` and co.). One of the most useful features, in my opinion, of those packages is the white noise bounding bars present in the ACF and PACF plots. You can see an example of them in [this section from Forecasting](https://otexts.com/fpp3/wn.html#wn). I find them extremely useful not only for seeing if a time series is stationary but also for determining which lags might serve as useful features. I noticed, however, that `plot_acf_diagnostics` doesn't include these bounding bars. I have two questions about this:

1. Is there a reason you chose not to recreate this functionality within `timetk`? 
2. If there isn't a reason, would you be okay with me opening a PR to add that functionality? My thought with this would be to recreate the blue, dashed line look from `fable` but make them an optional argument (ex. `.white_noise_bars = FALSE`) within `plot_acf_diagnostics`. 

What are your thoughts?

Thank you.

**Comment by mdancho84** [comment]
This would be a nice addition, Auggie. I like the argument name too. Making it optional is important. My preference is not to have them but to use the hover to show the value of the autocorrelation. But I understand that you and others may want the bars.

**Comment by realauggieheschmeyer** [comment]
Hey Matt. I have my changes staged and ready to be pushed, but I'm getting a permission denied message when I try to do so. I get the message regardless of whether I clone using HTTPS or SSH. Any ideas what I might be missing or are there permissions on the repo that I overlooked?

Thanks!

**Comment by mdancho84** [comment]
Hey Auggie,

Thanks for working on this. I’m not sure about why the PR isn’t working. 

I recently did one for rsample, and it usually requires forking a repo, making changes to your forked version, then making a pull request to merge the changes. 

Alternatively, if you provide the updates in a repo , I can work on getting the changes into the function provided it’s not too much work on my end. 

Let me know. 

Matt
