### ISSUE TITLE
Error in dirname(to) : chemin trop long

### ISSUE THREAD

**Issue by alifradi** [business-science/timetk#51]
Hey Matt,
I was trying your lab 36 and when I was trying to use timetk to plot a time series smoothed by fixed period (say 90 days like you did) I was having an error while executing these lines:

`data_formatted %>%
    summarise_by_time(date_time, .by = "day", global_active_power = sum(global_active_power)) %>%
    plot_time_series(date_time, global_active_power, .smooth_period = "90 days") `

**Comment by alifradi** [comment]
I think I fixed it but I don't know how ! I just reinstalled packages and restarted the RStudio session

**Comment by mdancho84** [comment]
The good-ole restart R Session! :)
