### ISSUE TITLE
tk_augment_lags() function is not working with grouped data

### ISSUE THREAD

**Issue by joaopcnogueira** [business-science/timetk#58]
I have tried the doc example of lagged variable within groups of data, but it does not work.

`
library(tidyverse)
library(timetk)

m4_monthly %>%
    group_by(id) %>%
    tk_augment_lags(value, .lags = 1)
`

The lag value of the first datapoint of the id = M2 is the last one of the id = 1. I think this should not be the behavior. The behaviour should be to place a NA value, as it already does on the first datapoint of the id = M1.

**Comment by vidarsumo** [comment]
I have the same problem. I'm using the development version of the package.

**Comment by mdancho84** [comment]
I’ll need to take a look. Will get it sorted out.

**Comment by joaopcnogueira** [comment]
I am using the latest CRAN version.

**Comment by mdancho84** [comment]
Nasty little bug. Forgot to `@export` the `tk_augment_lags.grouped_df` so it was performing ungrouped calculations.

**Comment by mdancho84** [comment]
Got it working now. 

``` r
library(tidyverse)
library(timetk)

m4_monthly %>%
    group_by(id) %>%
    slice(1:5) %>%
    tk_augment_lags(value, .lags = 1)
#> New names:
#> * NA -> ...1
#> New names:
#> * NA -> ...1
#> New names:
#> * NA -> ...1
#> New names:
#> * NA -> ...1
#> # A tibble: 20 x 4
#> # Groups:   id [4]
#>    id    date       value value_lag1
#>    <fct> <date>     <dbl>      <dbl>
#>  1 M1    1976-06-01  8000         NA
#>  2 M1    1976-07-01  8350       8000
#>  3 M1    1976-08-01  8570       8350
#>  4 M1    1976-09-01  7700       8570
#>  5 M1    1976-10-01  7080       7700
#>  6 M2    1976-06-01  2440         NA
#>  7 M2    1976-07-01  2490       2440
#>  8 M2    1976-08-01  2710       2490
#>  9 M2    1976-09-01  2290       2710
#> 10 M2    1976-10-01  1960       2290
#> 11 M750  1990-01-01  6370         NA
#> 12 M750  1990-02-01  6430       6370
#> 13 M750  1990-03-01  6520       6430
#> 14 M750  1990-04-01  6580       6520
#> 15 M750  1990-05-01  6620       6580
#> 16 M1000 1988-01-01  4170         NA
#> 17 M1000 1988-02-01  3800       4170
#> 18 M1000 1988-03-01  4160       3800
#> 19 M1000 1988-04-01  4260       4160
#> 20 M1000 1988-05-01  3910       4260
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by joaopcnogueira** [comment]
Thank you very much!
