### ISSUE TITLE
tk_augment_lag function suggestion

### ISSUE THREAD

**Issue by apsteinmetz** [business-science/timetk#65]
Hi, Matt. I was really pleased to see this new function.  It prompted me to get off my butt and work on a project that's been in my mind for a while.  I minor improvement that would be convenient is to have a `tk_augment_lead` function as well.  I do this manually like so:
```
df_lags <- df %>%
  # note negative number in lag range
  tk_augment_lags(feature,.lags = 0:-60,.names="auto") 
# fix names to remove minus sign
names(df_lags) <- names(df_lags) %>% str_replace_all("lag-","lead")
```
Thanks.

**Comment by mdancho84** [comment]
Hey Art, 
Great to hear from you. It seems like a quick fix is to adjust the naming convention for negative lags. I will need to look into this more, but I agree in having a more flexible option that makes leads is necessary. Good suggestion. I will incorporate soon. 

Cheers, 
Matt

**Comment by mdancho84** [comment]
This is complete. There is a new `tk_augment_leads()` function.
