### ISSUE TITLE
Is it possible to add annotation to non-interactive time-series plots?

### ISSUE THREAD

**Issue by lucazav** [business-science/timetk#69]
Is it possible to add annotations to a non-interactive plot?
It'd be great to be able to do something like this:

```
plot_time_series( ... , .interactive = FALSE ) %>%
    plotly::add_annotations( ... )
```

Any hint?
Thank you.

**Comment by mdancho84** [comment]
Do you mean adding annotations with ggplot? Yes - This is completely possible. When `.interactive = FALSE`, a `ggplot` object is returned and you can add (`+`) more layers just like you would with any `ggplot`.
