### ISSUE TITLE
Warn about unused parameters

### ISSUE THREAD

**Issue by nickv9** [business-science/timetk#73]
I thought I might hitting a bug when trying to use `summarize_by_time()` but I was just misspelling a parameter.

It would be ideal if the user could be warned, or the function could fail, when invalid arguments are specified.

``` r
library(tidyverse)
library(timetk)

# specified an unused parameter - adds a "type" column

m4_daily %>%
  summarise_by_time(
    .date_var = date,
    .by = "1 month", 
    month_total = sum(value), 
    type   = "ceiling") #missing the "." before type
#> # A tibble: 199 x 3
#>    date       month_total type   
#>    <date>           <dbl> <chr>  
#>  1 1978-06-01      72822. ceiling
#>  2 1978-07-01     283994. ceiling
#>  3 1978-08-01     291403. ceiling
#>  4 1978-09-01     279053. ceiling
#>  5 1978-10-01     287412. ceiling
#>  6 1978-11-01     273737. ceiling
#>  7 1978-12-01     280203. ceiling
#>  8 1979-01-01     277581. ceiling
#>  9 1979-02-01     251913. ceiling
#> 10 1979-03-01     281034. ceiling
#> # ... with 189 more rows

# correctly invoked performs the expected operation
m4_daily %>%
  summarise_by_time(
    .date_var = date,
    .by = "1 month", 
    month_total = sum(value), 
    .type   = "ceiling")
#> # A tibble: 199 x 2
#>    date       month_total
#>    <date>           <dbl>
#>  1 1978-07-01      72822.
#>  2 1978-08-01     283994.
#>  3 1978-09-01     291403.
#>  4 1978-10-01     279053.
#>  5 1978-11-01     287412.
#>  6 1978-12-01     273737.
#>  7 1979-01-01     280203.
#>  8 1979-02-01     277581.
#>  9 1979-03-01     251913.
#> 10 1979-04-01     281034.
#> # ... with 189 more rows
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mdancho84** [comment]
The challenge is that the `summarise()` function uses `...`, which makes it very difficult. 

For example, if you have a column called `type` and you really meant to apply a summarization to that column, I'd need to check if there was a column name in your data that could possibly be mistaken. I would then need to do this for all parameters. 

So what is better is double check your data, and make sure that ceiling was applied appropriately.

**Comment by nickv9** [comment]
I understand, pretty sure this has bitten me in other places. Thanks for the response!
