### ISSUE TITLE
reverse dependency issue

### ISSUE THREAD

**Issue by topepo** [business-science/timetk#79]
This might be a false postive but with the GH version of `recipes` has this error: 

* Version: 2.6.1
* GitHub: https://github.com/business-science/timetk
* Source code: https://github.com/cran/timetk
* Date/Publication: 2021-01-18 17:40:02 UTC
* Number of recursive dependencies: 188

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘timetk-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: tk_augment_differences
    > ### Title: Add many differenced columns to the data
    > ### Aliases: tk_augment_differences
    > 
    > ### ** Examples
    > 
    > library(tidyverse)
    ...
    ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ✖ dplyr::filter() masks stats::filter()
    ✖ dplyr::lag()    masks stats::lag()
    > library(timetk)
    > 
    > m4_monthly %>%
    +     group_by(id) %>%
    +     tk_augment_differences(value, .lags = 1:20)
    Error: tk_augment_differences(.differences) is missing.
    Execution halted
    ```

I'll be submitting `recipes` to CRAN soon. Let me know if there is something that we need to change.

**Comment by mdancho84** [comment]
Very weird. I don't see that issue on my end, but I can run some checks.

**Comment by mdancho84** [comment]
I think we are OK here. Closing this.
