### ISSUE TITLE
Compatibility with stats::stl(): only univariate series are allowed

### ISSUE THREAD

**Issue by malexan** [business-science/timetk#8]
I got a problem while working with `tk_ts()` and `stl()` together.

```r
# Original ts works fine
invisible(stl(AirPassengers, s.window = "periodic"))
# Covert to tibble
ts_tbl <- timetk::tk_tbl(AirPassengers)
ts <- timetk::tk_ts(ts_tbl, select = "value", 
              start = 1949, 
              end = 1960, 
              frequency = 12)
stl(ts, s.window = "periodic")
```
```
Error in stl(ts, s.window = "periodic") : 
  only univariate series are allowed
```

Based on [this](https://stackoverflow.com/a/28245744/3190110), `str()` rises the error from here: 
```r
 if (is.matrix(x)) 
        stop("only univariate series are allowed")
```
And from `?is.matrix`

> is.matrix returns TRUE if x is a vector and has a "dim" attribute of length 2) and FALSE otherwise. Note that a data.frame is not a matrix by this test. The function is generic: you can write methods to handle specific classes of objects, see InternalMethods.

**Comment by mdancho84** [comment]
I've requested a change to `stats::stl()`. Basically the code checks if the class is a `matrix` and assumes the matrix structure is multivariate which is not always the case. For example a matrix of 1 column should not cause an error.

I will see if there is anything I can do on the `timetk::tk_ts()` end since `stl` seems to work otherwise.

**Comment by apsteinmetz** [comment]
I ran into this too.  The workaround I found is to subset the time series object and use `s.window = "periodic"` with `stl()`. Using the vignette example of `alcohol_sales_ts()`:

`stl(alcohol_sales_ts[,1],s.window="periodic")`

works.

**Comment by muku1991** [comment]
use
stl(ts[,1], s.window = "periodic")
