### ISSUE TITLE
Enhancement: summarize_by_time, aggregate by week and choose the day the week starts

### ISSUE THREAD

**Issue by luifrancgom** [business-science/timetk#80]
Hello Matt Dancho

I am using the function summarize_by_time  and aggregating by week. By default the function uses Sunday as the first day of the week. 

I would like to know if you would consider allowing the user in the future to specify when a week starts when aggregating. 

In some countries people use Monday as the first day of the week. 

Best wishes and thank you for building timetk

**Comment by mdancho84** [comment]
Will take a look during next major update cycle. Should be a no brainer.

**Comment by mdancho84** [comment]
This should be complete. Try it out and you can now use `.week_start = 1` to convert to a Monday week-start.
