### ISSUE TITLE
Enhancement: Automate transformation of standardize_vec & standardize_inv_vec

### ISSUE THREAD

**Issue by jlindsteadt** [business-science/timetk#81]
I think a great feature to add would be the ability to auto-inverse the standardize_vec transformation without needing to copy the message that was printed during the original transformation, and manually plugging those values into standardized_inv_vec? Thanks in advance.

**Comment by mdancho84** [comment]
Will take a look during the next major update cycle.

**Comment by dmacoritto** [comment]
Hello mdancho84, I believe this would be a great feature. Did you have time to have a look at it ?

Thanks

**Comment by mdancho84** [comment]
## My objections

My preference is for you to use `recipes::step_normalize()`. This will store the transformations for preprocessing. 

The `standardize_vec()` returns a numeric vector, and we would need to modify it with attributes. But this gets very messy especially if you are doing multiple operations on the vector. 

AND, this is exactly why `recipes` exists. So I recommend using `recipes` preprocessing steps to track the essential transformation parameters. 

## Solution

Example solution to the programmatic storage of calculated transformation parameters.

``` r
library(dplyr)
library(timetk)
library(recipes)

df <-tibble( value = c(10, 5, 3, 5, 15, 18 ,19, 4, 0.1, 10))

recipe_spec <- df %>% 
    recipe(value ~ .) %>%
    step_normalize(value) %>%
    prep()

recipe_spec %>% tidy(1)
#> # A tibble: 2 x 4
#>   terms statistic value id             
#>   <chr> <chr>     <dbl> <chr>          
#> 1 value mean       8.91 normalize_Vxoia
#> 2 value sd         6.59 normalize_Vxoia
```

<sup>Created on 2022-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
