### ISSUE TITLE
White Noise CI in ACF Plots

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [business-science/timetk#85]
Hi @mdancho84 ,

I open this issue because  I would really like to talk about `plot_acf_diagnostics()`.

I would like to propose to change the ".show_white_noise_bars" argument of this function by default to TRUE. I really don't understand what is the reason to have it default to FALSE, since seeing the confidence intervals (at least in my opinion) seems to me something really important in this visualization and therefore I think it should be already there from the beginning. Although it may seem silly to change it, it took me some time to realize which was the argument I had to modify to activate this option (in fact, at the beginning I thought that this option did not exist).

Let's comment.

Best regards,

**Comment by mdancho84** [comment]
I've just updated this. Give it a look. https://business-science.github.io/timetk/reference/plot_acf_diagnostics.html

**Comment by AlbertoAlmuinha** [comment]
Perfect @mdancho84 , that’s ok for me!
