### ISSUE TITLE
Timetk Error: No applicable method for 'complement' applied to an object of class "c('rsplit', 'rlang_error', 'error', 'condition')"

### ISSUE THREAD

**Issue by shuerga** [business-science/timetk#86]
I get an error when running the 040_modeltime_forcasting.R (R version 3.6.3 64-bit)

![image](https://user-images.githubusercontent.com/33813980/124465459-733fe480-dd63-11eb-9062-8f66c2d0bf04.png)

**Comment by mdancho84** [comment]
First, try updating your software. I suspect you have old versions of recipes and/or timetk.

**Comment by shuerga** [comment]
Yeah. That worked. Thanks
