### ISSUE TITLE
Add a feature "showgap" in the function plot_time_series 

### ISSUE THREAD

**Issue by Mayalaroz** [business-science/timetk#87]
Hello,

I am using the function **plot_time_series**. It would be nice to have a feature that fill the gap between the actual and predicted values. For example, the function give this:

![image](https://user-images.githubusercontent.com/18237103/125452999-7880a345-817d-44c4-886a-062ec25bb528.png)

and I would like to have this:

![image](https://user-images.githubusercontent.com/18237103/125453071-6657a7de-5f53-4371-a3d7-08ee17cb81f8.png)

For the moment, I manually fill the gap.

**Comment by mdancho84** [comment]
How are you filling the gap? It looks like you are adding a data point to the actual data that is the forecast data.

**Comment by Mayalaroz** [comment]
Hello,

Sorry for my late answer. Yes, I actually duplicate a predictive value that lies in the gap and then assign it as actual.

**Comment by mdancho84** [comment]
I've decided not to do this.
