### ISSUE TITLE
Removing the white spaces between the plots resulting from timetk library in R

### ISSUE THREAD

**Issue by mallick84** [business-science/timetk#88]
I am trying to have very neat plots. So, trying to removes the whites spaces between the plots. I am using the timetk library. I have seen some of the examples related to the same questions, but those queries are mostly from grid.arrange or command +theme(plot.margin = unit(c(-0.25,0.5,-0.25,0.5), "lines")) from ggplot library. These concepts do not work on some of the plots commands with timetk library.
When there will be many plots, I want to have very neet plots.

```
library(tidyverse)
library(timetk)

    ## Case 1

walmart_sales_weekly %>%
    group_by(Store, Dept) %>%
    plot_anomaly_diagnostics(Date, Weekly_Sales,
                             .facet_ncol = 3, 
                             .interactive = TRUE)

```
![anomaly1](https://user-images.githubusercontent.com/34315322/127078500-4e7be5f5-24cf-485e-ab16-02424019ce4c.jpg)

```
## Case 2

walmart_sales_weekly %>%
  select(Date, Weekly_Sales,Size, Temperature,Fuel_Price, CPI, Unemployment )%>%
  pivot_longer(-Date)%>%
    group_by(name) %>%
  plot_seasonal_diagnostics(.date_var =  Date, 
                              .value =  value, 
                              .feature_set = 'month.lbl', 
                              .facet_vars = name
                              )

```

![sesonal1](https://user-images.githubusercontent.com/34315322/127078544-41b7e9f5-4eed-4d64-8139-caf2d4939f35.jpg)

```
## Case 3

walmart_sales_weekly %>%
  select(Date, Weekly_Sales,Size, Temperature,Fuel_Price, CPI, Unemployment )%>%
  pivot_longer(-Date)%>%
    group_by(name) %>%
  plot_time_series(.date_var =  Date, 
                              .value =  value, 
                             .facet_ncol = 2, .smooth = FALSE
                              )


```
![timeseries plot1](https://user-images.githubusercontent.com/34315322/127078769-4cd8552a-4f19-4ca4-9c96-7375ceff315f.jpg)

I required timeseries plots with tiketk library. I do not like to use any other library

![required](https://user-images.githubusercontent.com/34315322/127078651-eeb2d6da-8eab-4d5c-b1f9-c98c825673b9.jpg)

I have also raised this question in [stackoverflow](https://stackoverflow.com/questions/68537760/removing-the-white-spaces-between-the-plots-resulting-from-timetk-library-in-r)

**Comment by mdancho84** [comment]
This is something related to how plotly works. I responded in stackoverflow to use the `.interactive = FALSE`, which will help control the whitespace between facets. https://stackoverflow.com/questions/68537760/removing-the-white-spaces-between-the-plots-resulting-from-timetk-library-in-r/69953967#69953967
