### ISSUE TITLE
tk_get_timeseries_signature() returning wrong number of rows

### ISSUE THREAD

**Issue by FelipeCarrillo** [business-science/timetk#9]
I am running the FANG script and it is throwing an error because new_data is only generating 173 records while actual_future has 252. Can you explain how you made this script run? Thanks.

new_data <- train %>%
tk_index() %>%
tk_make_future_timeseries(n_future = 252, skip_values = holidays, inspect_weekdays = TRUE) %>%
tk_get_timeseries_signature()

pred_lm <- predict(fit_lm, newdata = new_data)

actual_future <- actual_future %>%
add_column(yhat = pred_lm)
Error: `.data` must have 252 rows, not 173

**Comment by mdancho84** [comment]
Please provide a reproducible example including the entire script you are running along with the libraries and data you are working with.

**Comment by FelipeCarrillo** [comment]
I am using the alcohol example here as it is easier to copy and paste the whole block of code from your page : http://www.business-science.io/code-tools/2017/05/02/timekit-0-2-0.html
`# Collect data and convert to yearmon regularized monthly data
beer_sales <- tq_get("S4248SM144NCEN", get = "economic.data", from = "2000-01-01")
beer_sales <- beer_sales %>%
    mutate(date = as.yearmon(date))

# Build training set and actual_future for comparison
train <- beer_sales %>%
    filter(date < 2014)
actual_future <- beer_sales %>%
    filter(date >= 2014)
 actual_future
 
# Add time series signature to training set
train <- train %>%
    tk_augment_timeseries_signature()

# Fit the linear regression model to predict price variable
fit_lm <- lm(price ~ ., data = train[,-1])

# Create the new date following the 3 steps
new_data <- train %>%
    tk_index() %>%
    tk_make_future_timeseries(n_future = 38) %>%
    tk_get_timeseries_signature()
##NOTE: tk_make_future_timeseries() =38 but it needs 43 

new_data

# Make predictions using predict
pred_lm <- predict(object = fit_lm, newdata = new_data)

# Add predictions to actual_future
actual_future <- actual_future %>%
    add_column(yhat = pred_lm) 
actual_future`
#I get an error here saying that actual future has 43 records and new_data only 38

**Comment by FelipeCarrillo** [comment]
Forgot to mention that I used library(timetk) and library(tidyquant)

**Comment by FelipeCarrillo** [comment]
Will this topic be addressed sometime?

**Comment by mdancho84** [comment]
This is an issue related to your attempt to add a column that is not the same length as the data frame. You will need to address that. Try this:
```
actual_future <- actual_future[1:38,] %>%
    add_column(yhat = pred_lm)
actual_future
```

**Comment by FelipeCarrillo** [comment]
That doesn't address the question at all...

**Comment by mdancho84** [comment]
Felipe, 
I guess I don't understand the question. I reproduced the exact example you provided and returned a complete result. What else am I to do? Help me help you.
-Matt
