### ISSUE TITLE
Unable to install timetk in rstudio on ubuntu 20.04

### ISSUE THREAD

**Issue by victormandela** [business-science/timetk#91]
Hello, I am unable install both timetk and tidyquant packages on ubuntu OS. I have tried the usuall install.packages("timetk") and remotes::install.. as adviced on github but it doesn't install! It gives me the following error
Installing package into ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
also installing the dependencies ‘quadprog’, ‘fracdiff’, ‘lmtest’, ‘tseries’, ‘urca’, ‘RcppArmadillo’, ‘forecast’

trying URL 'https://cloud.r-project.org/src/contrib/quadprog_1.5-8.tar.gz'
Content type 'application/x-gzip' length 36141 bytes (35 KB)
==================================================
downloaded 35 KB

trying URL 'https://cloud.r-project.org/src/contrib/fracdiff_1.5-1.tar.gz'
Content type 'application/x-gzip' length 63764 bytes (62 KB)
==================================================
downloaded 62 KB

trying URL 'https://cloud.r-project.org/src/contrib/lmtest_0.9-38.tar.gz'
Content type 'application/x-gzip' length 227052 bytes (221 KB)
==================================================
downloaded 221 KB

trying URL 'https://cloud.r-project.org/src/contrib/tseries_0.10-48.tar.gz'
Content type 'application/x-gzip' length 170342 bytes (166 KB)
==================================================
downloaded 166 KB

trying URL 'https://cloud.r-project.org/src/contrib/urca_1.3-0.tar.gz'
Content type 'application/x-gzip' length 682935 bytes (666 KB)
==================================================
downloaded 666 KB

trying URL 'https://cloud.r-project.org/src/contrib/RcppArmadillo_0.10.6.0.0.tar.gz'
Content type 'application/x-gzip' length 1673880 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://cloud.r-project.org/src/contrib/forecast_8.15.tar.gz'
Content type 'application/x-gzip' length 584703 bytes (570 KB)
==================================================
downloaded 570 KB

trying URL 'https://cloud.r-project.org/src/contrib/timetk_2.6.1.tar.gz'
Content type 'application/x-gzip' length 3793775 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘quadprog’ ...
** package ‘quadprog’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -fno-optimize-sibling-calls  -fvisibility=hidden -fpic -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -msse2 -mfpmath=sse   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong  -c aind.f -o aind.o
/bin/bash: gfortran: command not found
make: *** [/usr/lib/R/etc/Makeconf:191: aind.o] Error 127
ERROR: compilation failed for package ‘quadprog’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/quadprog’
Warning in install.packages :
  installation of package ‘quadprog’ had non-zero exit status
* installing *source* package ‘fracdiff’ ...
** package ‘fracdiff’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fdcore.c -o fdcore.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fdgam.c -o fdgam.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fdhess.c -o fdhess.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fdmin.c -o fdmin.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fdsim.c -o fdsim.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c pmult.c -o pmult.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o fracdiff.so fdcore.o fdgam.o fdhess.o fdmin.o fdsim.o init.o pmult.o -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: fracdiff.so] Error 1
ERROR: compilation failed for package ‘fracdiff’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/fracdiff’
Warning in install.packages :
  installation of package ‘fracdiff’ had non-zero exit status
* installing *source* package ‘lmtest’ ...
** package ‘lmtest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong  -c pan.f -o pan.o
/bin/bash: gfortran: command not found
make: *** [/usr/lib/R/etc/Makeconf:191: pan.o] Error 127
ERROR: compilation failed for package ‘lmtest’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/lmtest’
Warning in install.packages :
  installation of package ‘lmtest’ had non-zero exit status
* installing *source* package ‘urca’ ...
** package ‘urca’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong  -c UnitRootMacKinnon.f -o UnitRootMacKinnon.o
/bin/bash: gfortran: command not found
make: *** [/usr/lib/R/etc/Makeconf:191: UnitRootMacKinnon.o] Error 127
ERROR: compilation failed for package ‘urca’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/urca’
Warning in install.packages :
  installation of package ‘urca’ had non-zero exit status
* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++14 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++14 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -std=gnu++14 accepts -g... (cached) yes
checking whether we have a suitable tempdir... /tmp
checking whether R CMD SHLIB can already compile programs using OpenMP... yes
checking LAPACK_LIBS... system LAPACK found
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'   -I../inst/include  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppArmadillo.cpp -o RcppArmadillo.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'   -I../inst/include  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'   -I../inst/include  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fastLm.cpp -o fastLm.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/RcppArmadillo’
Warning in install.packages :
  installation of package ‘RcppArmadillo’ had non-zero exit status
ERROR: dependency ‘quadprog’ is not available for package ‘tseries’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/tseries’
Warning in install.packages :
  installation of package ‘tseries’ had non-zero exit status
ERROR: dependencies ‘fracdiff’, ‘lmtest’, ‘tseries’, ‘urca’, ‘RcppArmadillo’ are not available for package ‘forecast’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/forecast’
Warning in install.packages :
  installation of package ‘forecast’ had non-zero exit status
ERROR: dependency ‘forecast’ is not available for package ‘timetk’
* removing ‘/home/victor/R/x86_64-pc-linux-gnu-library/4.1/timetk’
Warning in install.packages :
  installation of package ‘timetk’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpEIOXH5/downloaded_packages’

**Comment by mdancho84** [comment]
We test on ubuntu so this looks like an issue isolated to your setup. I see that several dependencies that timetk depends on are not being installed. You might try installing from CRAN `install.packages("timetk")` rather than remotes.

**Comment by victormandela** [comment]
I managed to

**Comment by victormandela** [comment]
i managed to install on a standard installation. sorry for late response,
Matt.

**Comment by mdancho84** [comment]
Ok perfect. Thanks for the heads up.
