### ISSUE TITLE
expose `dir` argument of `facet_wrap()` for `plot_time_series()`

### ISSUE THREAD

**Issue by brshallo** [business-science/timetk#94]
There are some situations where facetted plots should be added by column rather than by row. It would be nice if users were able to pass in `dir = "v"` into the `plot_time_series()` function to change this behavior. Particularly in the case of `plot_time_series_cv_plan()` where a default of `dir = "v"` may actually be preferred. 

Example with current setup:

``` r
library(tidyverse)
library(rsample)
library(lubridate)
library(timetk)

set.seed(123)
p <- tibble::tibble(date = ymd(20180101) + days(0:364)) %>% 
  mutate(target = cumsum(sample(c(-1, 1), n(), TRUE))) %>% 
  rsample::sliding_period(index = date, period = "month", lookback = 3) %>% 
  timetk::tk_time_series_cv_plan() %>% 
  timetk::plot_time_series_cv_plan(
    date, target, 
    .facet_ncol = 2,
    .line_alpha = 0.5,
    .interactive = FALSE
  )

p
```

![](https://i.imgur.com/VBB3Ov7.png)

Currently can override this by adding another `facet_wrap()` ([SO solution](https://stackoverflow.com/questions/15034616/how-to-change-from-row-to-column-major-order-with-facet-wrap)):

``` r
# looked at p$data to find relevant column name of `facets_collapsed`
p + 
  facet_wrap(~.facets_collapsed, nrow = 4, dir = "v")
```

![](https://i.imgur.com/66B1fRA.png)

**Comment by mdancho84** [comment]
This should work now. I've added a new `.facet_dir` argument to `plot_time_series()`. Change this to "v" to make vertical.
