### ISSUE TITLE
Error when using non NA pad value in recently updated pad_by_time_function within dplyr groups

### ISSUE THREAD

**Issue by mitokic** [business-science/timetk#96]
Running pad_by_time within an existing dplyr group returns an error when trying to pad values with a number like 0. This breaks the previous functionality of the package. 

running the below code

library(tidyquant)
library(timetk)
library(dplyr)

FANG %>%
  group_by(symbol) %>%
  pad_by_time(.by = "day", 
              .pad_value = 0)

returns the following error

.date_var is missing. Using: date
Error: Problem with `mutate()` column `symbol`.
i `symbol = (function (x) ...`.
i `symbol` must be size 1459 or 1, not 5836.
i The error occurred in group 1: symbol = "AMZN".

**Comment by mdancho84** [comment]
Will take a look. This function was recently updated to improve speed which may have opened up this error.

**Comment by mdancho84** [comment]
This should be fixed now. Install the development version to get the fix. 

``` r
library(tidyquant)
library(timetk)
library(dplyr)

FANG %>%
    group_by(symbol) %>%
    pad_by_time(.by = "day",
                .pad_value = 1)
#> .date_var is missing. Using: date
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
#> # A tibble: 5,836 x 8
#> # Groups:   symbol [4]
#>    symbol date        open  high   low close  volume adjusted
#>    <chr>  <date>     <dbl> <dbl> <dbl> <dbl>   <dbl>    <dbl>
#>  1 AMZN   2013-01-02  256.  258.  253.  257. 3271000     257.
#>  2 AMZN   2013-01-03  257.  261.  256.  258. 2750900     258.
#>  3 AMZN   2013-01-04  258.  260.  257.  259. 1874200     259.
#>  4 AMZN   2013-01-05    1     1     1     1        1       1 
#>  5 AMZN   2013-01-06    1     1     1     1        1       1 
#>  6 AMZN   2013-01-07  263.  270.  263.  268. 4910000     268.
#>  7 AMZN   2013-01-08  267.  269.  264.  266. 3010700     266.
#>  8 AMZN   2013-01-09  268.  270.  265.  266. 2265600     266.
#>  9 AMZN   2013-01-10  269.  269.  262.  265. 2863400     265.
#> 10 AMZN   2013-01-11  265.  268.  264.  268. 2413300     268.
#> # ... with 5,826 more rows
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
