### ISSUE TITLE
Use EMA in timetk::tk_augment_slidify() 

### ISSUE THREAD

**Issue by Steviey** [business-science/timetk#99]
Hello,

can we use functions like EMA from within timetk::tk_augment_slidify() 
and if so, how?

Thank you.

**Comment by Steviey** [comment]
Can't get it working. Basically I want the same result as with tidyquant::geom_ma(), but without plotting. I also tried timetk::tk_augment_slidify() without success.

`            idx=12
            df <- expand.grid(
                 n1 =  rnorm(idx, mean=15, sd=5)
                ,n2 =  rnorm(idx, mean=15, sd=5)
            )      
            df<-df %>% dplyr::mutate(id=row_number()) %>% relocate(id)

            lm_roll <- slidify(~EMA(.x,n=7,wilder=TRUE), .period = 144, .unlist = FALSE, .align = "right")
            df      <- df %>% dplyr::mutate(rolling_lm = lm_roll(n1))

            testPlot <- suppressWarnings(ggplot(df,aes(x=id)))
            testPlot <- testPlot + suppressWarnings(tidyquant::geom_ma(aes(x=id,y=n1),wilder=TRUE,ma_fun=EMA,n=7,size=1.7,color='green',linetype='solid'))
            #testPlot <- testPlot + suppressWarnings(geom_line(aes(y=rolling_lm),color='red'))
            print(testPlot)`

**Comment by mdancho84** [comment]
Were you able to get it working?

**Comment by Steviey** [comment]
I had the wrong idea.
